
name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build Application
      run: mvn clean package -DskipTests

    - name: Deploy to EC2
      run: |
        chmod +x deploy.sh
        ./deploy.sh
